accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('forgot-password/', views.forgot_password, name='forgot-password'),
    path('reset-password/<uidb64>/<token>/', views.reset_password_validate, name='reset-password-validate'),
    path('reset-password/', views.reset_password, name='reset-password'),
]

greatkart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

media_config = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('category/', include('category.urls')),
    path('accounts/', include('accounts.urls')),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
] + media_config

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.home, name='home')
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from phonenumber_field.modelfields import PhoneNumberField

class MyAccountManager(BaseUserManager):
    def create_user(self, first_name, last_name, username, email, password=None):
        if not email:
            raise ValueError('User must have an email address')
        
        if not username:
            raise ValueError('User must have an username')
        
        user = self.model(
            email = self.normalize_email(email),
            username = username,
            first_name = first_name,
            last_name = last_name,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user
    
    def create_superuser(self, first_name, last_name, email, username, password):
        user = self.create_user(
            email= self.normalize_email(email),
            username = username,
            password = password,
            first_name = first_name,
            last_name = last_name,
        )
        user.is_admin = True
        user.is_active = True
        user.is_staff = True
        user.is_superadmin = True
        user.save(using=self._db)
        return user

class Account(AbstractBaseUser):
    class Meta:
        verbose_name = 'Account'
        verbose_name_plural = 'Accounts'

    def __str__(self) -> str:
        return self.email
    
    def has_perm(self, perm, obj=None):
        return self.is_admin
    
    def has_module_perms(self, add_label):
        return True
    
    objects = MyAccountManager()

    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    username = models.CharField(max_length=50, unique=True)
    email = models.EmailField(max_length=100, unique=True)
    phone_number = PhoneNumberField()

    #required
    date_joined = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    is_superadmin = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name']

accounts/forms.py
from django import forms
from .models import Account

class RegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Enter Password',
    }))
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Confirm Password'
    }))
    class Meta:
        model = Account
        fields = ['first_name', 'last_name', 'phone_number', 'email', 'password']

    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs['placeholder'] = 'Enter First Name'
        self.fields['last_name'].widget.attrs['placeholder'] = 'Enter Last Name'
        self.fields['email'].widget.attrs['placeholder'] = 'Enter Your Email'
        self.fields['phone_number'].widget.attrs['placeholder'] = 'Enter Phone Number'
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

    def clean(self):
        cleaned_data = super(RegistrationForm, self).clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password != confirm_password:
            raise forms.ValidationError(
                'Passwords does\'t match!'
            )

accounts/views.py
from django.shortcuts import render, redirect, HttpResponse
from .forms import RegistrationForm
from .models import Account
from django.contrib import messages, auth
from django.contrib.auth.decorators import login_required
from .decorators import user_not_authenticated

# Email Verification
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes
from django.core.mail import EmailMessage

@user_not_authenticated
def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            phone_number = form.cleaned_data['phone_number']
            email = form.cleaned_data['email']
            if email:
                username = email.split('@')[0]
                password = form.cleaned_data['password']
                user = Account.objects.create_user(first_name=first_name, last_name=last_name, email=email, username=username, password=password)
                user.phone_number = phone_number
                user.save()

                # USER ACCOUNT ACTIVATION
                current_site = get_current_site(request)
                mail_subject = 'Please activate your greatkart account'
                message = render_to_string('accounts/account_verification_email.html', {
                    'user': user,
                    'domain': current_site.domain,
                    'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                    'token': default_token_generator.make_token(user), 
                })
                to_email = [email]  # Make sure to_email is a list
                send_email = EmailMessage(mail_subject, message, to=to_email)
                try:
                    send_email.send()
                    # messages.success(request, 'Please check your email to activate your account.')
                except Exception as e:
                    return HttpResponse("Email sending failed: " + str(e))
                return redirect('/accounts/login/?command=verification&email='+email)
            else:
                messages.error(request, 'Email is required.')
    else:
        form = RegistrationForm()

    context = {
        'form': form,
    }
    return render(request, 'accounts/register.html', context)

@user_not_authenticated
def login(request):
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']

        user = auth.authenticate(email=email, password=password)

        if user:
            auth.login(request, user)
            # messages.success(request, 'You are now logged in')
            return redirect('home:home')
        else:
            messages.error(request, 'Invalid Credentials!')
            return redirect('accounts:login')
    return render(request, 'accounts/login.html')

@login_required
def logout(request):
    auth.logout(request)
    return redirect('accounts:login')

def activate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = Account._default_manager.get(pk=uid)
    except(TypeError, ValueError, OverflowError, Account.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        messages.success(request, 'Your account has been activated!')
        return redirect('accounts:login')
    else:
        messages.error(request, 'Invalid activation link!')
        return redirect('accounts:register')

@login_required
def dashboard(request):
    return render(request, 'accounts/dashboard.html')

def forgot_password(request):
    if request.method == 'POST':
        email = request.POST['email']
        if Account.objects.filter(email=email).exists():
            user = Account.objects.get(email__exact=email)

            # FORGOT PASSWORD EMAIL
            current_site = get_current_site(request)
            mail_subject = 'Reset your password'
            message = render_to_string('accounts/reset_password_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': default_token_generator.make_token(user), 
            })
            to_email = [email]  # Make sure to_email is a list
            send_email = EmailMessage(mail_subject, message, to=to_email)
            try:
                send_email.send()
                messages.success(request, 'Password reset email has been sent to your email address')
                return redirect('accounts:login')
            except Exception as e:
                return HttpResponse("Email sending failed: " + str(e))
        else:
            messages.error(request, 'Account doesn\'t exist!')
            return redirect('accounts:forgot-password')
    return render(request, 'accounts/forgot_password.html')

def reset_password_validate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = Account._default_manager.get(pk=uid)
    except(TypeError, ValueError, OverflowError, Account.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        request.session['uid'] = uid
        messages.success(request, 'Please reset your password')
        return redirect('accounts:reset-password')
    else:
        messages.error(request, 'This link has been expired!')
        return redirect('accounts:login')
    
def reset_password(request):
    if request.method == 'POST':
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']

        if password == confirm_password:
            uid = request.session.get('uid')
            user = Account.objects.get(pk=uid)
            user.set_password(password)
            user.save()
            messages.success(request, 'Password reset successful')
            return redirect('accounts:login')
        else:
            messages.error(request, 'Passwords doesn\'t match!')
            return redirect('accounts:reset-password')
    else:
        return render(request, 'accounts/reset_password.html')

templates/accounts/account_verification_email.html
{% autoescape off %}

Hi {{user.first_name}},

Please click on the below link to activate your greatkart account.

http://{{domain}}{% url "accounts:activate" uidb64=uid token=token %}

If you think it's not you, ignore this email.

{% endautoescape %}

templates/accounts/dashboard.html
{% extends "base.html" %}

{% block title %}Dashboard{% endblock title %}

{% block content %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y bg">

    <div class="container">
        <div class="row">
        <aside class="col-md-3">
            <!--   SIDEBAR   -->
            <ul class="list-group">
                <a class="list-group-item active" href="#"> My order history </a>
                <a class="list-group-item" href="#"> Transactions </a>
                <a class="list-group-item" href="#"> Return and refunds </a>
                <a class="list-group-item" href="#">Settings </a>
                <a class="list-group-item" href="#"> My Selling Items </a>
                <a class="list-group-item" href="#"> Received orders </a>
            </ul>
            <br>
            <a class="btn btn-light btn-block" href="{% url "accounts:logout" %}"> <i class="fa fa-power-off"></i> <span class="text">Log out</span> </a> 
            <!--   SIDEBAR .//END   -->
        </aside>
        <main class="col-md-9">
            <article class="card">
            <header class="card-header">
                <strong class="d-inline-block mr-3">Order ID: 6123456789</strong>
                <span>Order Date: 16 December 2018</span>
            </header>
            <div class="card-body">
                <div class="row"> 
                    <div class="col-md-8">
                        <h6 class="text-muted">Delivery to</h6>
                        <p>Michael Jackson <br>  
                        Phone +1234567890 Email: myname@pixsellz.com <br>
                        Location: Home number, Building name, Street 123,  Tashkent, UZB <br> 
                        P.O. Box: 100123
                         </p>
                    </div>
                    <div class="col-md-4">
                        <h6 class="text-muted">Payment</h6>
                        <span class="text-success">
                            <i class="fab fa-lg fa-cc-visa"></i>
                            Visa  **** 4216  
                        </span>
                        <p>Subtotal: $356 <br>
                         Shipping fee:  $56 <br> 
                         <span class="b">Total:  $456 </span>
                        </p>
                    </div>
                </div> <!-- row.// -->
            </div> <!-- card-body .// -->
            <div class="table-responsive">
            <table class="table table-hover">
                <tr>
                    <td width="65">
                        <img src="../images/items/1.jpg" class="img-xs border">
                    </td>
                    <td> 
                        <p class="title mb-0">Product name goes here </p>
                        <var class="price text-muted">USD 145</var>
                    </td>
                    <td> Seller <br> Nike clothing </td>
                    <td width="250"> <a href="#" class="btn btn-outline-primary">Track order</a> <a href="#" class="btn btn-light"> Details </a> </td>
                </tr>
                <tr>
                    <td>
                        <img src="../images/items/2.jpg" class="img-xs border">
                    </td>
                    <td> 
                        <p class="title mb-0">Another name goes here </p>
                        <var class="price text-muted">USD 15</var>
                    </td>
                    <td> Seller <br> ABC shop </td>
                    <td> <a href="#" class="btn btn-outline-primary">Track order</a> <a href="#" class="btn btn-light"> Details </a> </td>
                </tr>
                <tr>
                    <td>
                        <img src="../images/items/3.jpg" class="img-xs border">
                    </td>
                    <td> 
                        <p class="title mb-0">The name of the product  goes here </p>
                        <var class="price text-muted">USD 145</var>
                    </td>
                    <td> Seller <br> Wallmart </td>
                    <td> <a href="#" class="btn btn-outline-primary">Track order</a> <a href="#" class="btn btn-light"> Details </a> </td>
                </tr>
            </table>
            </div> <!-- table-responsive .end// -->
            </article> <!-- order-group.// --> 
        </main>
    </div> <!-- row.// -->
    </div>
    
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock content %}

templates/accounts/forgot_password.html
{% extends "base.html" %}

{% block title %}Login{% endblock title %}

{% block content %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y" style="min-height:84vh">

    <!-- ============================ COMPONENT LOGIN   ================================= -->

        <div class="card mx-auto" style="max-width: 400px; margin-top:100px;">
          <div class="card-body">
          {% include 'includes/alerts.html' %}
          <h4 class="card-title mb-4">Forgot Password</h4>
          <form action="{% url "accounts:forgot-password" %}" method="POST">
            {% csrf_token %}
              <div class="form-group">
                 <input type="email" class="form-control" placeholder="Email Address" name="email">
              </div> <!-- form-group// -->
              
              <div class="form-group">
                  <a href="{% url "accounts:login" %}" class="float-right">Remember Password? Login</a> 
               
              </div> <!-- form-group form-check .// -->
              <div class="form-group">
                  <button type="submit" class="btn btn-primary btn-block">Submit</button>
              </div> <!-- form-group// -->    
          </form>
          </div> <!-- card-body.// -->
        </div> <!-- card .// -->
    
         <p class="text-center mt-4">Don't have account? <a href="{% url "accounts:register" %}">Register</a></p>
         <br><br>
    <!-- ============================ COMPONENT LOGIN  END.// ================================= -->
    
</section>
    <!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock content %}

templates/accounts/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock title %}

{% block content %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y" style="min-height:84vh">

    <!-- ============================ COMPONENT LOGIN   ================================= -->

    {% if request.GET.command == 'verification' %}
    
    <div class="container mx-auto alert alert-info text-center" role="alert" style="max-width: 1024px; margin-top:100px;">
      Thank you for registering with us. We have sent you an verification email to {{request.GET.email}}
      <br><br>
      Already verified? <a href="{% url "accounts:login" %}">Login</a>
    </div>

    {% else %}

        <div class="card mx-auto" style="max-width: 380px; margin-top:100px;">
          <div class="card-body">
          {% include 'includes/alerts.html' %}
          <h4 class="card-title mb-4">Sign in</h4>
          <form action="{% url "accounts:login" %}" method="POST">
            {% csrf_token %}
              <div class="form-group">
                 <input type="email" class="form-control" placeholder="Email Address" name="email">
              </div> <!-- form-group// -->
              <div class="form-group">
                <input type="password" class="form-control" placeholder="Password" name="password">
              </div> <!-- form-group// -->
              
              <div class="form-group">
                  <a href="#" class="float-right">Forgot password?</a> 
               
              </div> <!-- form-group form-check .// -->
              <div class="form-group">
                  <button type="submit" class="btn btn-primary btn-block"> Login  </button>
              </div> <!-- form-group// -->    
          </form>
          </div> <!-- card-body.// -->
        </div> <!-- card .// -->
    
         <p class="text-center mt-4">Don't have account? <a href="{% url "accounts:register" %}">Register</a></p>
         <br><br>
    <!-- ============================ COMPONENT LOGIN  END.// ================================= -->

    {% endif %}
    
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock content %}

templates/accounts/register.html
{% extends "base.html" %}

{% block title %}Register{% endblock title %}

{% block content %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y">

    <!-- ============================ COMPONENT REGISTER   ================================= -->
    <div class="card mx-auto" style="max-width:520px; margin-top:40px;">
        <article class="card-body">
          {% include 'includes/alerts.html' %}
          <header class="mb-4">
            <h4 class="card-title">Sign up</h4>
          </header>
          <form method="post" action="{% url 'accounts:register' %}">
            {% csrf_token %}
            <div class="form-row">
              <div class="col form-group">
                <label>First name</label>
                {{form.first_name}}
              </div>
              <!-- form-group end.// -->
              <div class="col form-group">
                <label>Last name</label>
                {{form.last_name}}
              </div>
              <!-- form-group end.// -->
            </div>
            <!-- form-row end.// -->
            <div class="form-row">
              <div class="form-group col-md-6">
                <label>Email</label>
                {{form.email}}
                <small class="form-text text-muted">We'll never share your email with anyone else.</small>
              </div>
              <!-- form-group end.// -->
              <div class="form-group col-md-6">
                <label>Phone Number</label>
                {{form.phone_number}}
              </div>
              <!-- form-group end.// -->
            </div>
            <!-- form-row.// -->
            <div class="form-row">
              <div class="form-group col-md-6">
                <label>Create password</label>
                {{form.password}}
              </div>
              <!-- form-group end.// -->
              <div class="form-group col-md-6">
                <label>Repeat password</label>
                {{form.confirm_password}}
              </div>
              <!-- form-group end.// -->
            </div>
            <div class="form-group">
              <button type="submit" class="btn btn-primary btn-block"> Register </button>
            </div>
            <!-- form-group// -->
            {{form.email.errors}}
            {{form.non_field_errors}}
          </form>
        </article>
        <!-- card-body.// -->
    </div>
      <!-- card .// -->
      <p class="text-center mt-4">Have an account? <a href="{% url "accounts:login" %}">Log In</a></p>
      <br><br>      
    <!-- ============================ COMPONENT REGISTER  END.// ================================= -->
    
    
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->
    

{% endblock content %}

templates/accounts/reset_password.html
{% extends "base.html" %}

{% block title %}Login{% endblock title %}

{% block content %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y" style="min-height:84vh">

    <!-- ============================ COMPONENT LOGIN   ================================= -->

        <div class="card mx-auto" style="max-width: 380px; margin-top:100px;">
          <div class="card-body">
          {% include 'includes/alerts.html' %}
          <h4 class="card-title mb-4">Reset Password</h4>
          <form action="{% url "accounts:reset-password" %}" method="POST">
            {% csrf_token %}
              <div class="form-group">
                <input type="password" class="form-control" placeholder="Create Password" name="password">
              </div> <!-- form-group// -->
              <div class="form-group">
                <input type="password" class="form-control" placeholder="Confirm Password" name="confirm_password">
              </div> <!-- form-group// -->
              
              <div class="form-group">
                  <a href="{% url "accounts:forgot-password" %}" class="float-right">Forgot password?</a> 
               
              </div> <!-- form-group form-check .// -->
              <div class="form-group">
                  <button type="submit" class="btn btn-primary btn-block"> Reset  </button>
              </div> <!-- form-group// -->    
          </form>
          </div> <!-- card-body.// -->
        </div> <!-- card .// -->
    
         <p class="text-center mt-4">Don't have account? <a href="{% url "accounts:register" %}">Register</a></p>
         <br><br>
    <!-- ============================ COMPONENT LOGIN  END.// ================================= -->
    
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock content %}

templates/accounts/reset_password_email.html
{% autoescape off %}

Hi {{user.first_name}},

As requested, please click below link to reset your password.
http://{{domain}}{% url "accounts:reset-password-validate" uidb64=uid token=token %}

If you think it's not you, please ignore this email.

{% endautoescape %}