carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'
urlpatterns = [
    path('', views.cart, name='cart'),
    path('add-cart/<slug:product_slug>/', views.add_cart, name='add-cart'),
    path('remove-cart/<slug:product_slug>/<int:cart_item_id>/', views.remove_cart, name='remove-cart'),
    path('remove-cart-item/<slug:product_slug>/<int:cart_item_id>/', views.remove_cart_item, name='remove-cart-item'),
]

greatkart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

media_config = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('category/', include('category.urls')),
    path('accounts/', include('accounts.urls')),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
] + media_config

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.home, name='home')
]

store/urls.py
from django.urls import path
from . import views

app_name = 'store'
urlpatterns = [
    path('', views.store, name='store'),
    path('category/<slug:category_slug>/', views.store, name='products-by-category'),
    path('category/<slug:category_slug>/<slug:product_slug>/', views.product_detail, name='products-detail'),
    path('search/', views.search, name='search'),
]

carts/models.py
from django.db import models
from store.models import Product, Variation

class Cart(models.Model):
    class Meta:
        verbose_name = 'Cart'
        verbose_name_plural = 'Cart'
        ordering = ['-date_added']

    def __str__(self) -> str:
        return self.cart_id

    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

class CartItem(models.Model):
    class Meta:
        verbose_name = 'Cart Item'
        verbose_name_plural = 'Cart Items'

    def __unicode__(self) -> str:
        return self.product
    
    def sub_total(self):
        return self.product.price * self.quantity

    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    is_active = models.BooleanField(default=True)
    variations = models.ManyToManyField(Variation, blank=True)

carts/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from store.models import Product, Variation
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist

def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart

def add_cart(request, product_slug):
    product = Product.objects.get(slug=product_slug) # get the product
    product_variation = []
    if request.method == 'POST':
        for item in request.POST:
            key = item
            value = request.POST[key]

            try:
                variation = Variation.objects.get(product=product, variation_category__iexact=key, variation_value__iexact=value)
                product_variation.append(variation)
            except: pass

    try:
        cart = Cart.objects.get(cart_id=_cart_id(request)) # get the cart using cart_id present in the session
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
            cart_id = _cart_id(request)
        )
    cart.save()

    is_cart_item_exists = CartItem.objects.filter(product=product, cart=cart).exists()
    if is_cart_item_exists:
        cart_item = CartItem.objects.filter(product=product, cart=cart)
        # existing variations -> database
        # current variation -> product_variation
        # item_id -> database
        existing_variation_list = []
        id = []
        for item in cart_item:
            existing_variation = item.variations.all()
            existing_variation_list.append(list(existing_variation))
            id.append(item.id)

        if product_variation in existing_variation_list:
            # increase the cart item quantity
            index = existing_variation_list.index(product_variation)
            item_id = id[index]
            item = CartItem.objects.get(product=product, id=item_id)
            item.quantity += 1
            item.save()
        else:
            # create a new cart item
            item = CartItem.objects.create(product=product, quantity=1, cart=cart)
            if len(product_variation) > 0:
                item.variations.clear()
                item.variations.add(*product_variation)
            item.save()
    else: 
        cart_item = CartItem.objects.create(
            product = product,
            quantity = 1,
            cart = cart,
        )
        if len(product_variation) > 0:
            cart_item.variations.clear()
            cart_item.variations.add(*product_variation)
        cart_item.save()
    return redirect('carts:cart')

def remove_cart_item(request, product_slug, cart_item_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, slug=product_slug)
    cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
    cart_item.delete()
    return redirect('carts:cart')

def cart(request, total=0, quantity=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity
        tax = (2 * total) / 100
        grand_total = total + tax
    except ObjectDoesNotExist:
        pass

    context = {
        'total': total, 
        'quantity': quantity,
        'cart_items': cart_items,
        'tax': tax,
        'grand_total': grand_total,
    } 
    return render(request, 'carts/cart.html', context)

def remove_cart(request, product_slug, cart_item_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, slug=product_slug)
    try:
        cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
        if cart_item.quantity > 1:
            cart_item.quantity -= 1
            cart_item.save()
        else:
            cart_item.delete()
    except:
        pass
    return redirect('carts:cart')

templates/carts/cart.html
{% extends "base.html" %}
{% load static %}

{% block title %}Cart{% endblock title %}

{% block content %}

<!-- ========================= SECTION CONTENT START// ========================= -->
<section class="section-content padding-y bg">
    <div class="container">
    
    <!-- ============================ COMPONENT 1 ================================= -->
    
    {% if not cart_items %}

    <h2 class="text-center">Your Shopping Cart is Empty</h2>
    <br>
    <div class="text-center">
        <a href="{% url "store:store" %}" class="btn btn-primary">Continue Shopping</a>
    </div>

    {% else %}

    <div class="row">
        <aside class="col-lg-9">
    <div class="card">
    <table class="table table-borderless table-shopping-cart">
    <thead class="text-muted">
    <tr class="small text-uppercase">
      <th scope="col">Product</th>
      <th scope="col" width="120">Quantity</th>
      <th scope="col" width="120">Price</th>
      <th scope="col" class="text-right" width="200"> </th>
    </tr>
    </thead>
    <tbody>

    {% for cart_item in cart_items %} 
    <tr>
        <td>
            <figure class="itemside align-items-center">
                <div class="aside"><img src="{{cart_item.product.images.url}}" class="img-sm" draggable="false"></div>
                <figcaption class="info">
                    <a href="{{cart_item.product.get_url}}" class="title text-dark">{{cart_item.product.product_name}}</a>
                    <p class="text-muted small">
                        {% if cart_item.variations.all %}
                            {% for item in cart_item.variations.all  %}
                                {{item.variation_category|capfirst}} : {{item.variation_value|capfirst}}<br>
                            {% endfor %}
                        {% endif %}
                    </p>
                </figcaption>
            </figure>
        </td>
        <td> 
            <!-- col.// -->
                        <div class="col"> 
                            <div class="input-group input-spinner">
                                <div class="input-group-prepend">
                                <a href="{% url "carts:remove-cart" cart_item.product.slug cart_item.id %}" class="btn btn-light" type="button" id="button-plus"> <i class="fa fa-minus"></i> </a>
                                </div>
                                <input type="text" class="form-control"  value="{{cart_item.quantity}}">
                                <div class="input-group-append">
                                <form action="{% url "carts:add-cart" cart_item.product.slug %}" method="POST">
                                    {% csrf_token %}
                                    {% for item in cart_item.variations.all %}
                                        <input type="hidden" name="{{item.variation_category|lower}}" value="{{item.variation_value|capfirst}}">
                                    {% endfor %}
                                    <button class="btn btn-light" type="submit" id="button-minus"> <i class="fa fa-plus"></i> </button>
                                </form>
                                </div>
                            </div> <!-- input-group.// -->
                        </div> <!-- col.// -->
        </td>
        <td> 
            <div class="price-wrap"> 
                <var class="price">{{cart_item.sub_total}}</var> 
                <small class="text-muted">{{cart_item.product.price}} each</small> 
            </div> <!-- price-wrap .// -->
        </td>
        <td class="text-right"> 
            <a href="{% url "carts:remove-cart-item" cart_item.product.slug cart_item.id %}" onclick="return confirm('Are you sure you want to delete this item?')" class="btn btn-danger"><i class="fas fa-trash"></i></i></a>
        </td>
    </tr>
    {% endfor %}   

    </tbody>
    </table>
    </div> <!-- card.// -->
    
        </aside> <!-- col.// -->
        <aside class="col-lg-3">
    
            <div class="card">
            <div class="card-body">
                <dl class="dlist-align">
                  <dt>Total price:</dt>
                  <dd class="text-right">{{total}}</dd>
                </dl>
                <dl class="dlist-align">
                  <dt>Tax:</dt>
                  <dd class="text-right">{{tax}}</dd>
                </dl>
                <dl class="dlist-align">
                  <dt>Grand Total:</dt>
                  <dd class="text-right text-dark b"><strong>{{grand_total}}</strong></dd>
                </dl>
                <hr>
                <p class="text-center mb-3">
                    <img src="{% static "./images/misc/payments.png" %}" height="26">
                </p>
                <a href="./place-order.html" class="btn btn-primary btn-block"> Checkout </a>
                <a href="{% url "store:store" %}" class="btn btn-light btn-block">Continue Shopping</a>
            </div> <!-- card-body.// -->
            </div> <!-- card.// -->
    
    </aside> <!-- col.// -->
    
    
    </div> <!-- row.// -->
    {% endif %}
    <!-- ============================ COMPONENT 1 END .// ================================= -->
    
    </div> <!-- container .//  -->
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock content %}