carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'
urlpatterns = [
    path('', views.cart, name='cart'),
    path('add-cart/<slug:product_slug>/', views.add_cart, name='add-cart'),
    path('remove-cart/<slug:product_slug>/<int:cart_item_id>/', views.remove_cart, name='remove-cart'),
    path('remove-cart-item/<slug:product_slug>/<int:cart_item_id>/', views.remove_cart_item, name='remove-cart-item'),
]

greatkart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

media_config = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('category/', include('category.urls')),
    path('accounts/', include('accounts.urls')),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
] + media_config

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.home, name='home')
]

store/urls.py
from django.urls import path
from . import views

app_name = 'store'
urlpatterns = [
    path('', views.store, name='store'),
    path('category/<slug:category_slug>/', views.store, name='products-by-category'),
    path('category/<slug:category_slug>/<slug:product_slug>/', views.product_detail, name='products-detail'),
    path('search/', views.search, name='search'),
]

store/models.py
from django.db import models
from autoslug import AutoSlugField
from djmoney.models.fields import MoneyField
from category.models import Category
from django.urls import reverse

class Product(models.Model):
    class Meta:
        verbose_name = 'Product'
        verbose_name_plural = 'Products'
        ordering = ['-created_date']

    def __str__(self) -> str:
        return self.product_name
    
    # Update slug if product_name has changed
    def save(self, *args, **kwargs):
        if self.product_name and self.slug != self.product_name:
            self.slug = self.product_name
        super().save(*args, **kwargs)

    def get_url(self):
        return reverse('store:products-detail', args=[self.category.slug, self.slug])

    product_name = models.CharField(max_length=200)
    slug = AutoSlugField(populate_from='product_name', unique=True)
    product_description = models.TextField(max_length=500, blank=True)
    price = MoneyField(max_digits=14, decimal_places=2, default_currency='INR')
    discount_price = MoneyField(max_digits=14, decimal_places=2, default_currency='INR', null=True, blank=True)
    images = models.ImageField(upload_to='images/products')
    stock = models.PositiveIntegerField()
    is_available = models.BooleanField(default=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

class VariationManager(models.Manager):
    def colors(self):
        return super(VariationManager, self).filter(variation_category='color', is_active=True)
    
    def sizes(self):
        return super(VariationManager, self).filter(variation_category='size', is_active=True)

variation_category_choice = (
    ('color', 'color'),
    ('size', 'size'),
)
class Variation(models.Model):
    class Meta:
        verbose_name = 'Variation'
        verbose_name_plural = 'Variations'

    def __str__(self):
        return self.variation_value

    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_category = models.CharField(max_length=100, choices=variation_category_choice)
    variation_value = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now_add=True)

    objects = VariationManager()

store/views.py
from django.shortcuts import render, get_object_or_404, HttpResponse
from .models import Product
from category.models import Category
from carts.models import CartItem
from carts.views import _cart_id
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Q

def store(request, category_slug=None):
    categories = None
    products = None

    if category_slug:
        categories = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.all().filter(category=categories, is_available=True)
        paginator = Paginator(products, 1)
        page = request.GET.get('page')
        paged_products = paginator.get_page(page)
        product_count = products.count()
    else:
        products = Product.objects.all().filter(is_available=True).order_by('id')
        paginator = Paginator(products, 6)
        page = request.GET.get('page')
        paged_products = paginator.get_page(page)
        product_count = products.count()
    context = {'products': paged_products, 'product_count': product_count,}
    return render(request, 'store/store.html', context)

def product_detail(request, category_slug, product_slug):
    try:
        single_product = Product.objects.get(category__slug=category_slug, slug=product_slug)
        in_cart = CartItem.objects.filter(cart__cart_id=_cart_id(request), product=single_product).exists()
    except Exception as e:
        raise e
    context = {'single_product': single_product,
               'in_cart': in_cart,
            }
    return render(request, 'store/product_detail.html', context)

def search(request):
    products = []
    product_count = 0 
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        if not len(keyword) < 3:
                products = Product.objects.order_by('-created_date').filter(
                    Q(product_description__icontains=keyword) | 
                    Q(product_name__icontains=keyword) |
                    Q(category__category_name__icontains=keyword)
                )
                product_count = products.count()
    context = {'products': products,
               'product_count': product_count,
            }
    return render(request, 'store/store.html', context)

templates/store/product_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{single_product.product_name}}{% endblock title %}

{% block content %}

<!-- ========================= SECTION CONTENT START// ========================= -->
<section class="section-content padding-y bg">
    <div class="container">
    
    <!-- ============================ COMPONENT 1 ================================= -->
    <div class="card">
        <div class="row no-gutters">
            <aside class="col-md-6">
    <article class="gallery-wrap"> 
        <div class="img-big-wrap">
           <a href="#"><img src="{{single_product.images.url}}" draggable="false"></a>
        </div> <!-- img-big-wrap.// -->
    </article> <!-- gallery-wrap .end// -->
            </aside>
            <main class="col-md-6 border-left">

  <form action="{% url "carts:add-cart" single_product.slug %}" method="POST">
    {% csrf_token %}
    <article class="content-body">
    
    <h2 class="title">{{single_product.product_name}}</h2>
    
    <div class="mb-3"> 
        <var class="price h4">{{single_product.price}}</var>
    </div> 
    
    <p>{{single_product.product_description}}</p>
    
    
    <hr>
        <div class="row">
            <div class="item-option-select">
                <h6>Choose Color</h6>
                  <select name="color" class="form-control" required>
                    <option value="" disabled selected>Select</option>
                    {% for i in single_product.variation_set.colors %}
                    <option value="{{i.variation_value|lower}}">{{i.variation_value|capfirst}}</option>
                    {% endfor %}
                  </select>
            </div>
        </div>

        <div class="row">
            <div class="item-option-select">
                <h6>Select Size</h6>
                <select name="size" class="form-control" required>
                  <option value="" disabled selected>Select</option>
                  {% for i in single_product.variation_set.sizes %}
                  <option value="{{i.variation_value|lower}}">{{i.variation_value|capfirst}}</option>
                  {% endfor %}
                </select>
            </div>
        </div> 

        <hr>
        {% if single_product.stock %}
            <button type="submit" class="btn btn-primary"> <span class="text">Add to Cart</span> <i class="fas fa-shopping-cart"></i></button>
        {% else %}
            <button class="btn btn-primary" disabled>Out of Stock <i class="fas fa-shopping-cart"></i></button>
        {% endif %}
    </article> <!-- product-info-aside .// -->
  </form>
            </main> <!-- col.// -->
        </div> <!-- row.// -->
    </div> <!-- card.// -->
    <!-- ============================ COMPONENT 1 END .// ================================= -->
    
    <br>
    
    <div class="row">
                <div class="col-md-9">
    
        <header class="section-heading">
            <h3>Customer Reviews </h3>  
            
        </header>
    
        <article class="box mb-3">
            <div class="icontext w-100">
                <img src="{% static "./images/avatars/avatar1.jpg" %}" class="img-xs icon rounded-circle">
                <div class="text">
                    <span class="date text-muted float-md-right">24.04.2020 </span>  
                    <h6 class="mb-1">Mike John </h6>
                    
                </div>
            </div> <!-- icontext.// -->
            <div class="mt-3">
                <p>
                    Dummy comment Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                    quis nostrud exercitation ullamco laboris nisi ut aliquip
                </p>	
            </div>
        </article>
    
        
    
        </div> <!-- col.// -->
    </div> <!-- row.// -->
    
    
    </div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock content %}

templates/store/store.html
{% extends "base.html" %}
{% load static %}

{% block title %}Store{% endblock title %}

{% block content %}

<!-- ========================= SECTION PAGETOP ========================= -->
<section class="section-pagetop bg">
    <div class="container">
        {% if 'search' in request.path %}
            <h2 class="title-page">Search result</h2>
        {% else %}
            <h2 class="title-page">Our Store</h2>
        {% endif %}
    </div> <!-- container //  -->
</section>
<!-- ========================= SECTION INTRO END// ========================= -->

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y">
    <div class="container">
    
    <div class="row">
        <aside class="col-md-3">
            
    <div class="card">
        <article class="filter-group">
            <header class="card-header">
                <a href="#" data-toggle="collapse" data-target="#collapse_1" aria-expanded="true" class="">
                    <i class="icon-control fa fa-chevron-down"></i>
                    <h6 class="title">Categories</h6>
                </a>
            </header>
            <div class="filter-content collapse show" id="collapse_1" style="">
                <div class="card-body">
                    
                    <ul class="list-menu">
                    <li><a href="{% url "store:store" %}">All Products</a></li>
                    {% for category in links %}
                    <li><a href="{{category.get_url}}">{{category.category_name}}</a></li>
                    {% endfor %}
                    </ul>
                    
                </div> <!-- card-body.// -->
            </div>
        </article> <!-- filter-group  .// -->
        <article class="filter-group">
            <header class="card-header">
                <a href="#" data-toggle="collapse" data-target="#collapse_4" aria-expanded="true" class="">
                    <i class="icon-control fa fa-chevron-down"></i>
                    <h6 class="title">Sizes </h6>
                </a>
            </header>
            <div class="filter-content collapse show" id="collapse_4" style="">
                <div class="card-body">
                  <label class="checkbox-btn">
                    <input type="checkbox">
                    <span class="btn btn-light"> XS </span>
                  </label>
    
                  <label class="checkbox-btn">
                    <input type="checkbox">
                    <span class="btn btn-light"> SM </span>
                  </label>
    
                  <label class="checkbox-btn">
                    <input type="checkbox">
                    <span class="btn btn-light"> LG </span>
                  </label>
    
                  <label class="checkbox-btn">
                    <input type="checkbox">
                    <span class="btn btn-light"> XXL </span>
                  </label>
            </div><!-- card-body.// -->
            </div>
        </article> <!-- filter-group .// -->
        
        <article class="filter-group">
            <header class="card-header">
                <a href="#" data-toggle="collapse" data-target="#collapse_3" aria-expanded="true" class="">
                    <i class="icon-control fa fa-chevron-down"></i>
                    <h6 class="title">Price range </h6>
                </a>
            </header>
            <div class="filter-content collapse show" id="collapse_3" style="">
                <div class="card-body">
                    
                    <div class="form-row">
                    <div class="form-group col-md-6">
                      <label>Min</label>
                      <!-- <input class="form-control" placeholder="$0" type="number"> -->
                          <select class="mr-2 form-control">
                            <option value="0">$0</option>
                            <option value="50">$50</option>
                            <option value="100">$100</option>
                            <option value="150">$150</option>
                            <option value="200">$200</option>
                            <option value="500">$500</option>
                            <option value="1000">$1000</option>
                        </select>
                    </div>
                    <div class="form-group text-right col-md-6">
                      <label>Max</label>
                          <select class="mr-2 form-control">
                            <option value="50">$50</option>
                            <option value="100">$100</option>
                            <option value="150">$150</option>
                            <option value="200">$200</option>
                            <option value="500">$500</option>
                            <option value="1000">$1000</option>
                            <option value="2000">$2000+</option>
                        </select>
                    </div>
                    </div> <!-- form-row.// -->
                    <button class="btn btn-block btn-primary">Apply</button>
                </div><!-- card-body.// -->
            </div>
        </article> <!-- filter-group .// -->
        
    </div> <!-- card.// -->
    
        </aside> <!-- col.// -->
        <main class="col-md-9">
    
    <header class="border-bottom mb-4 pb-3">
            <div class="form-inline">
                <span class="mr-md-auto">{{product_count}} Items found </span>
                
            </div>
    </header><!-- sect-heading -->
    
    <div class="row">
        {% if not products %}
            <div class="text-center">
                <h2>No results found</h2>
            </div>
        {% else %}
            {% for product in products %}
                <div class="col-md-4">
                    <figure class="card card-product-grid">
                        <div class="img-wrap">
                            <a href="{{product.get_url}}">
                                <img src="{{product.images.url}}" draggable="false">
                            </a> 
                        </div> <!-- img-wrap.// -->
                        <figcaption class="info-wrap">
                            <div class="fix-height">
                                <a href="{{product.get_url}}" class="title">{{product.product_name|title}}</a>
                                <div class="price-wrap mt-2">
                                    <span class="price">{{product.price}}</span>
                                    {% if product.discount_price %}
                                    <del class="price-old">{{product.discount_price}}</del>
                                    {% endif %}
                                </div> <!-- price-wrap.// -->
                            </div>
                            <a href="{{product.get_url}}" class="btn btn-block btn-primary"> <span class="text">View Details</span></a>
                        </figcaption>
                    </figure>
                </div> <!-- col.// -->
            {% endfor %}
        {% endif %}
    </div> <!-- row end.// -->
    
    
    
    <nav class="mt-4" aria-label="Page navigation sample">
        {% if products.has_other_pages %}
            <ul class="pagination">
                {% if products.has_previous %}
                <li class="page-item"><a class="page-link" href="?page={{products.previous_page_number}}">Prev</a></li>
                {% else %}
                <li class="page-item disabled"><a class="page-link" href="">Prev</a></li>
                {% endif %}

                {% for i in products.paginator.page_range %}
                    {% if products.number == i %}
                        <li class="page-item active"><a class="page-link" href="">{{i}}</a></li>
                    {% else %}
                        <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
                    {% endif %}
                {% endfor %}

                {% if products.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{products.next_page_number}}">Next</a></li>
                {% else %}
                <li class="page-item disabled"><a class="page-link" href="">Next</a></li>
                {% endif %}
            </ul>
        {% endif %}
    </nav>
    
        </main> <!-- col.// -->
    
    </div>
    
    </div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock content %}